name = "erudify-web"
main = "result/build/worker/shim.mjs"
compatibility_date = "2024-07-13"

routes = [
  { pattern = "erudify.org", zone_name = "erudify.org", custom_domain = true },
]

[assets]
directory = "result/assets"

[build]
command = """
nix build .#erudify-web-dev
"""

[env.prebuilt.build]
command = ""

[env.dev.build]
command = """
mkdir -p result/assets/pkg &&
cp public/* result/assets/ &&
tailwindcss --minify -i style/tailwind.css -o result/assets/style.css &&
wasm-pack build --out-dir result/assets/pkg --no-typescript --no-opt --target web --out-name client --features hydrate --no-default-features &&
worker-build --no-opt --features ssr --no-default-features &&
rm -fr result/build &&
mv build result/
"""
