name = "erudify-web"
main = "build/worker/shim.mjs"
compatibility_date = "2024-07-13"

routes = [
	{ pattern = "lemmih.org/*", zone_name = "lemmih.org" }
]

[build]
command = "mkdir -p pkg && cp public/* pkg/ && npx tailwindcss --minify -i style/tailwind.css -o pkg/style.css && wasm-pack build --no-typescript --release --target web --out-name client --features hydrate --no-default-features && worker-build --release --features ssr --no-default-features"
