[package]
name = "erudify-web"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
dioxus = { version = "0.5.1", features = ["web"] }
dioxus-logger = "0.5.1"
manganis = "0.2.2"
serde = "1.0.204"
web-sys = { version = "0.3.69", features = ["HtmlAudioElement", "MediaQueryList", "Window"] }
