name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Configure caching
      uses: Swatinem/rust-cache@v2

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - uses: sigoden/install-binary@v1
      with:
        repo: WebAssembly/binaryen
        name: wasm-opt

    - name: Install worker-build
      run: cargo install --locked worker-build

    - uses: nanasess/setup-chromedriver@v2
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '126.0.6478.182'
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &

    - name: Run website
      run: |
        npx wrangler@latest build
        npx wrangler@latest dev &
        echo "waiting"
        timeout 120 sh -c 'until nc -z $0 $1; do sleep 1; done' 127.0.0.1 8787

    - name: E2E
      run: |
        cd e2e
        cargo run
